import textwrap
from abc import ABC
from subtitle_saver.i_subtitle_saver_strategy import ISubtitleSaverStrategy

class ISubtitleGenerator(ABC):
    """Interface for the different subtitle creation strategies
    """

    def create_subtitles(self, file_path:str, audio_saving_strategy: ISubtitleSaverStrategy):
        """Creates the subtitles of a given audio
        """
        pass

    def change_model(self, language:str):
        """Changes the model based on a provided language

        Args:
            language (str): the model language
        """
    
    @staticmethod
    def __format_time(seconds: float) -> str:
        h = int(seconds // 3600)
        m = int((seconds % 3600) // 60)
        s = int(seconds % 60)
        cs = int((seconds - int(seconds)) * 100)
        return f"{h}:{m:02}:{s:02}.{cs:02}"
    
    def convert_to_ass(self, json_subtitles_timestamps:dict[str,str,str]):
        word_per_subtitle = 3

        template = textwrap.dedent("""\
        [Script Info]
        ; Script generated by ChatGPT
        Title: Pretty Subtitles Centered Middle
        ScriptType: v4.00+
        Collisions: Normal
        PlayDepth: 0

        [V4+ Styles]
        Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
        ; PrimaryColour: &HAABBGGRR (alpha, blue, green, red)
        ; Yellow text: Red=FF, Green=FF, Blue=00, no transparency (00)
        ; White background (BackColour) fully opaque: &H00FFFFFF
        Style: Default,Arial,15,&H0000FFFF,&H000000FF,&H00000000,&H00FFFFFF,1,0,0,0,100,100,0,0,1,2,0,8,0,0,30,1

        [Events]
        Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
        """)
        for index in range(0, len(json_subtitles_timestamps), word_per_subtitle):
            group = json_subtitles_timestamps[index:index+word_per_subtitle]
            start = self.__format_time(group[0]["start"])
            end = self.__format_time(group[-1]["end"])
            words = " ".join(word['word'].capitalize() for word in group)
            template += f"Dialogue: 0,{start},{end},Default,,0,0,0,,{words}\n"


        return template